name: Deploy to Windows Dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  windows-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DEV_DB_HOST }}
      DB_PW: ${{ secrets.DEV_DB_PW}}
      DB_USER: ${{ secrets.DEV_DB_USER }}
      DB_NAME: ${{ secrets.DEV_DB_NAME }}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v1

      - run: |
          touch .env
          echo DB_HOST="$DB_HOST" >> .env
          echo DB_PW="$DB_PW" >> .env
          echo DB_USER="$DB_USER" >> .env
          echo DB_NAME="$DB_NAME" >> .env
          echo CLIENT_ID ="$CLIENT_ID" >> .env
          echo CLIENT_SECRET = "$CLIENT_SECRET" >> .env

      - run: npm run bundle

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: deploy/
          remote: c:/nodeapps/performance-backend
          recursive: true
          host: "performancedev.oc.edu"
          username: "david.north"
          privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
          password: ${{ secrets.PASSWORD }}

      - name: Command via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: '.\deploy-performance-backend'
          host: "performancedev.oc.edu"
          username: "david.north"
          privateKey: ${{ secrets.DEV_WIN_SERVER_SSH_KEY  }}
